import Head from 'next/head';
import Dashboard from '@/components/dashboard/Dashboard';
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import { useAuth } from '../../../../contexts/AuthContext';

const App = () => {
  const { user } = useAuth();
  const router = useRouter();


  // This effect runs when the component mounts or when 'user' or 'router' change.
  useEffect(() => {
    // Check if there is a logged-in user. If 'user' is not null, a user is logged in.
    if (user && user.userType == "patient") {
      // Construct the URL to the user's dashboard based on their unique user ID (UID).
      // This URL will navigate the user to their personalized dashboard.
      router.push(`/patient/${user.uid}/dashboard`);
    }
  }, [user, router]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" type="image/svg+xml" />
      </Head>
      {user && <Dashboard />}
    </>
  );
};

export default App;
