import Head from 'next/head';
import { useAuth } from '../../contexts/AuthContext';
import Dashboard from '@/components/dashboard/Dashboard';

const App = () => {
  const { user } = useAuth();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" type="image/svg+xml" />
      </Head>
      {user && <Dashboard />}
    </>
  );
};

export default App;
