import Head from 'next/head';
import { AuthProvider, useAuth } from '../../contexts/AuthContext';
import Navbar from '@/components/navbar/Navbar';
import Dashboard from '@/components/dashboard/Dashboard';

const MyPage = () => {
  const { user } = useAuth();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {user && <Dashboard />}
      <main></main>
    </>
  );
};

const WrappedMyPage = () => {
  return (
    <AuthProvider>
      <MyPage />
    </AuthProvider>
  );
};

export default WrappedMyPage;